# Creates initial state for a master's integration environment sandbox

- name: setup master's integration environment
  hosts: all
  become: True
  gather_facts: True
  vars:
    - env_path: /edx/app/edxapp/edxapp_env
    - edxapp_venv_dir: /edx/app/edxapp/venvs/edxapp
    - edxapp_code_dir: "/edx/app/edxapp/edx-platform"

  tasks:
    - name: debug task
      shell: echo {{env_path}} {{foo}} {{bar}}

    - name: create user api access request
    shell: >
      . {{ env_path }} && {{ edxapp_venv_dir }}/bin/python manage.py lms create_api_access_request {{username}}
      --site-name {{site_name}} --reason {{reason}} --website {{website}} --create-config --production
    args:
      chdir: "{{ edxapp_code_dir }}"
